---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker-rt
  name: machine-config-worker-rt
spec:
  config:
    ignition:
      version: 2.2.0
    storage:
      files:
        -
          contents:
            source: data:text/plain;base64,IyEvYmluL2Jhc2gKaWYgWyAtZiAvZXRjL2NlbnRvcy1yZWxlYXNlIF07IHRoZW4KICAgIHN1ZG8gdGVlIC9ldGMveXVtLnJlcG9zLmQvQ2VudE9TLXJ0LnJlcG8gPi9kZXYvbnVsbCA8PEVPRgojIENlbnRPUy1ydC5yZXBvCgpbcnRdCm5hbWU9Q2VudE9TLTcgLSBydApiYXNldXJsPWh0dHA6Ly9taXJyb3IuY2VudG9zLm9yZy9jZW50b3MvXCRyZWxlYXNldmVyL3J0L1wkYmFzZWFyY2gvCmdwZ2NoZWNrPTEKZ3Bna2V5PWZpbGU6Ly8vZXRjL3BraS9ycG0tZ3BnL1JQTS1HUEctS0VZLUNlbnRPUy03CkVPRgogICAgeXVtIHVwZGF0ZSAteQogICAgeXVtIHJlbW92ZSAteSB0dW5lZAogICAgeXVtIGluc3RhbGwgLXkga2VybmVsLXJ0IHJ0LXRlc3RzIHR1bmVkLXByb2ZpbGVzLXJlYWx0aW1lCmVsc2UKICAgICMgYWRkIHJpZ2h0IHJlYWx0aW1lIHBhY2thZ2UgZGVwZW5kaW5nIG9uIHZlcnNpb24KICAgIGlmIFtbICIkKGNhdCAvZXRjL3JlZGhhdC1yZWxlYXNlKSIgPX4gIk1haXBvIiBdXTsgdGhlbgogICAgICAgIHN1YnNjcmlwdGlvbi1tYW5hZ2VyIHJlcG9zIC0tZW5hYmxlIHJoZWwtNy1zZXJ2ZXItcnQtcnBtcwogICAgZWxzZQogICAgICAgIHN1YnNjcmlwdGlvbi1tYW5hZ2VyIHJlcG9zIC0tZW5hYmxlIHJoZWwtOC1mb3IteDg2XzY0LXJ0LXJwbXMKICAgIGZpCiAgICB5dW0gZ3JvdXBpbnN0YWxsIC15IFJUCmZpCgpjbWRsaW5lX3JlYWx0aW1lPSIraXNvbGNwdXM9XCR7aXNvbGF0ZWRfY29yZXN9IGludGVsX3BzdGF0ZT1kaXNhYmxlIG5vc29mdGxvY2t1cCBubWlfd2F0Y2hkb2c9MCBhdWRpdD0wIG1jZT1vZmYga3RocmVhZF9jcHVzPTAgaXJxYWZmaW5pdHk9MCBza2V3X3RpY2s9MSBwcm9jZXNzb3IubWF4X2NzdGF0ZT0xIGlkbGU9cG9sbCBpbnRlbF9pZGxlLm1heF9jc3RhdGU9MCBpbnRlbF9wc3RhdGU9ZGlzYWJsZSBpbnRlbF9pb21tdT1vbiBpb21tdT1wdCBkZWZhdWx0X2h1Z2VwYWdlc3o9XCR7aHVnZXBhZ2Vfc2l6ZV9kZWZhdWx0fSBodWdlcGFnZXN6PVwke2h1Z2VwYWdlX3NpemV9IGh1Z2VwYWdlcz1cJHtodWdlcGFnZV9udW19IG5vaHo9b24gbm9oel9mdWxsPVwke2lzb2xhdGVkX2NvcmVzfSByY3Vfbm9jYnM9XCR7aXNvbGF0ZWRfY29yZXN9IgoKc2VkIC1pICdzfF5jbWRsaW5lX3JlYWx0aW1lLip8Y21kbGluZV9yZWFsdGltZT0nIiR7Y21kbGluZV9yZWFsdGltZX0iJ3wnIC91c3IvbGliL3R1bmVkL3JlYWx0aW1lL3R1bmVkLmNvbmYgIAoKIyBhZGQgZHluYW1pYyBpc29sYXRlZCBjb3JlcwpjcCAvdG1wL3JlYWx0aW1lLXZhcmlhYmxlcy5jb25mIC9ldGMvdHVuZWQvcmVhbHRpbWUtdmFyaWFibGVzLmNvbmYKZWNobyAiaXNvbGF0ZWRfY29yZXM9Mi0kKCgkKGNhdCAvcHJvYy9jcHVpbmZvIHwgYXdrICcvXnByb2Nlc3Nvci97cHJpbnQgJDN9JyB8IHdjIC1sKSAtMSApKSIgPj4gL2V0Yy90dW5lZC9yZWFsdGltZS12YXJpYWJsZXMuY29uZgoKc3lzdGVtY3RsIHN0YXJ0IHR1bmVkCnN5c3RlbWN0bCBlbmFibGUgdHVuZWQKdHVuZWQtYWRtIHByb2ZpbGUgcmVhbHRpbWUKCnRvdWNoIC9vcHQvcnRfZXhlY3V0ZWQKcmVib290Cg==
          filesystem: root
          mode: 0777
          path: /opt/setup_rt.sh
    systemd:
      units:
        -
          contents: |
            [Unit]
            Description=One time service to install rt and tuned profile
            After=network-online.target
            ConditionPathExists=!/opt/rt_executed
            [Service]
            Type=oneshot
            ExecStart=/opt/setup_rt.sh
            [Install]
            WantedBy=multi-user.target
          enabled: true
          name: install_realtime.service
