bases:
- ../../../base/02_cluster-addons
resources:
- 00_config-ran/00_machine-config-pool-worker-rt.yaml
- 00_config-ran/00_machine-config-worker-rt-env-vars.yaml
- 00_config-ran/01_machine-config-worker-rt.yaml
- 00_config-ran/02_override_tuning_deployment.yaml
- 00_config-ran/03_disable_tuning_deployment.yaml
- 00_config-ran/04_add_tuned_affinity.yaml
- 00_config-ran/05_add_static_policy_label.yaml
- 00_config-ran/06_add_static_kubeletconfig.yaml
- 01_sriov-network-operator/01_namespace.yaml
- 01_sriov-network-operator/02_sriov-operatorgroup.yaml
- 01_sriov-network-operator/03_sriov-sub.yaml
- 02_ptp-daemonset/01_ptp-machineconfig.yaml
- 02_ptp-daemonset/02_namespace.yaml
- 02_ptp-daemonset/03_serviceaccount.yaml
- 02_ptp-daemonset/04_rbac.yaml
- 02_ptp-daemonset/05_configmap.yaml
- 02_ptp-daemonset/06_daemonset.yaml
- 03_storage/00_ceph_common.yaml
- 03_storage/01_ceph_operator_openshift.yaml
- 03_storage/02_ceph_cluster.yaml
- 03_storage/03_ceph_storage_class.yaml
- 03_storage/04_ceph_storage_filesystem.yaml
- 03_storage/05_ceph_image_registry_pvc.yaml
- 04_nodes/00_node_definitions.yaml

